Arkanoid MONOGAME: Arkanoid.Components.SpriteRenderer Class Reference
Arkanoid.Components.SpriteRenderer Class Reference
Component class taking care of drawing texture it contains
Public Member Functions
SpriteRenderer (Texture2D sprite, SpriteBatch spriteBatch, Transform transform)
void DrawSprite ()
Method drawing sprite on the screen. Does nothing if sprite batch or texture doesn't exist
Rectangle GetRectangle ()
Function calculating texture rectangle on the scene
int GetWidth ()
Calculate scene width of the texture
int GetHeight ()
Calculate scene height of the texture
Data Fields
Texture2D Sprite
SpriteBatch SpriteBatch
Color Color
Private Attributes
Transform transform
Detailed Description
Component class taking care of drawing texture it contains
Definition at line 9 of file SpriteRenderer.cs.
Constructor & Destructor Documentation
SpriteRenderer()
Arkanoid.Components.SpriteRenderer.SpriteRenderer (Texture2D sprite, SpriteBatch spriteBatch, Transform transform) inline
Definition at line 17 of file SpriteRenderer.cs.
         {
             this.Sprite = sprite;
             this.SpriteBatch = spriteBatch;
             this.transform = transform;
             Color = Color.White;
         }
Member Function Documentation
DrawSprite()
void Arkanoid.Components.SpriteRenderer.DrawSprite () inline
Method drawing sprite on the screen. Does nothing if sprite batch or texture doesn't exist
Definition at line 28 of file SpriteRenderer.cs.
Referenced by Arkanoid.DrawableEntity.Draw(), and Arkanoid.GameObjects.HeartHP.Draw().
         {
             if(SpriteBatch!=null && Sprite!=null)
                 SpriteBatch.Draw(Sprite, GetRectangle(), Color);
         }
GetHeight()
int Arkanoid.Components.SpriteRenderer.GetHeight () inline
Calculate scene height of the texture
Returns
scaled texture height
Definition at line 58 of file SpriteRenderer.cs.
References Arkanoid.Components.Transform.Scale.
Referenced by Arkanoid.GameObjects.Ball.CheckBounds().
         {
             return (int)(Sprite.Bounds.Height * transform.Scale.Y);
         }
GetRectangle()
Rectangle Arkanoid.Components.SpriteRenderer.GetRectangle () inline
Function calculating texture rectangle on the scene
Returns
rectangle fitting texture on the scene
Definition at line 38 of file SpriteRenderer.cs.
References Arkanoid.Components.Transform.Position.
Referenced by Arkanoid.GameObjects.Ball.GetCollider(), and Arkanoid.GameObjects.Paddle.GetCollider().
         {
             return new Rectangle((int)transform.Position.X - GetWidth() / 2 , //Position X
                                  (int)transform.Position.Y - GetHeight() / 2 , //Position Y
                                  GetWidth(), GetHeight());
         }
GetWidth()
int Arkanoid.Components.SpriteRenderer.GetWidth () inline
Calculate scene width of the texture
Returns
scaled texture width
Definition at line 49 of file SpriteRenderer.cs.
References Arkanoid.Components.Transform.Scale.
Referenced by Arkanoid.GameObjects.Ball.BounceFromCollider(), Arkanoid.GameObjects.Ball.CheckBounds(), Arkanoid.GameObjects.Paddle.CheckBounds(), and Arkanoid.GameObjects.HeartHP.Draw().
         {
             return (int)(Sprite.Bounds.Width * transform.Scale.X);
         }
Field Documentation
Color
Color Arkanoid.Components.SpriteRenderer.Color
Definition at line 13 of file SpriteRenderer.cs.
Sprite
Texture2D Arkanoid.Components.SpriteRenderer.Sprite
Definition at line 11 of file SpriteRenderer.cs.
Referenced by Arkanoid.GameObjects.Ball.OnPaddle(), and Arkanoid.GameObjects.Brick.UpdateSpriteState().
SpriteBatch
SpriteBatch Arkanoid.Components.SpriteRenderer.SpriteBatch
Definition at line 12 of file SpriteRenderer.cs.
transform
Transform Arkanoid.Components.SpriteRenderer.transform private
Definition at line 15 of file SpriteRenderer.cs.
The documentation for this class was generated from the following file:
Arcanoid/Scripts/Utils/Components/SpriteRenderer.cs