Arkanoid MONOGAME: Arkanoid.Scenes.MainGame Class Reference
Arkanoid.Scenes.MainGame Class Reference
Main game scene
Public Member Functions
MainGame (GameController game)
override void Update (GameTime gameTime)
Every frame removes destroyed entities, invokes update and draw functions, checks collisions between physics bodies. Also updates and draws UI.
override void Draw (GameTime gameTime)
Draws entities and then draws UI
override void Initialize ()
Initialize function. Invoked on start of the game
Public Member Functions inherited from Arkanoid.Scene
Scene (GameController game)
void DestroyEntity (Entity entity)
Removes entity from every possible manager
Private Member Functions
void CheckBallLoss ()
void GameOver ()
void CheckRestartInput ()
void LoadTextures ()
void LoadFonts ()
void InitializeBackground ()
void InitializeBall ()
void InitializePaddle ()
void InitializeUI ()
void InitializeHeartHP ()
void InitializeTexts ()
void InitializeGameOverForeground ()
void InitializeMapGenerator ()
void PrepareNewGame ()
void GenerateMap ()
Private Attributes
Vector2 textSpace = new Vector2(0, 5)
const string GAME_OVER_TEXT = "Game Over"
const string RESTART_TEXT = "Press ENTER to restart"
const int INIT_LIFE_COUNT = 3
MapGenerator mapGenerator
DrawableEntity background
Ball ball
Paddle paddle
HeartHP hp
DrawableEntity gameOverForeground
TextLabel gameOverText
TextLabel restartText
bool gameOver
Additional Inherited Members
Protected Attributes inherited from Arkanoid.Scene
GameController game
SpriteBatch spriteBatch
EntitiesManager managerUI
EntitiesManager entitiesManager
PhysicsManager physicsManager
List< Entity > entities
Detailed Description
Main game scene
Definition at line 14 of file MainGame.cs.
Constructor & Destructor Documentation
MainGame()
Arkanoid.Scenes.MainGame.MainGame (GameController game) inline
Definition at line 35 of file MainGame.cs.
                                              : base(game)
         {
             //DUMMY
         }
Member Function Documentation
CheckBallLoss()
void Arkanoid.Scenes.MainGame.CheckBallLoss () inline private
Definition at line 53 of file MainGame.cs.
References Arkanoid.GameObjects.HeartHP.GetLifeCount(), Arkanoid.GameObjects.HeartHP.RemoveHeart(), Arkanoid.GameObjects.Ball.SetOnPaddle(), Arkanoid.DrawableEntity.SpriteRenderer, and Arkanoid.Entity.Transform.
         {
             if (hp.GetLifeCount() > 0 && ball.Transform.Position.Y == game.ScreenBounds.Bottom - ball.SpriteRenderer.GetHeight() / 2)
             {
                 hp.RemoveHeart();
                 ball.SetOnPaddle(true);
                 if (hp.GetLifeCount() == 0)
                 {
                     GameOver();
                 }
             }
         }
CheckRestartInput()
void Arkanoid.Scenes.MainGame.CheckRestartInput () inline private
Definition at line 76 of file MainGame.cs.
         {
             if(Keyboard.GetState().IsKeyDown(Keys.Enter))
             {
                 PrepareNewGame();
             }
         }
Draw()
override void Arkanoid.Scenes.MainGame.Draw (GameTime gameTime) inline virtual
Draws entities and then draws UI
Parameters
gameTime object containing game time passed from class Game
Reimplemented from Arkanoid.Scene.
Definition at line 88 of file MainGame.cs.
Referenced by Arkanoid.GameController.Draw().
         {
             base.Draw(gameTime);
         }
GameOver()
void Arkanoid.Scenes.MainGame.GameOver () inline private
Definition at line 67 of file MainGame.cs.
         {
             DestroyEntity(ball);
             managerUI.AddEntity(gameOverForeground);
             managerUI.AddEntity(gameOverText);
             managerUI.AddEntity(restartText);
             gameOver = true;
         }
GenerateMap()
void Arkanoid.Scenes.MainGame.GenerateMap () inline private
Definition at line 233 of file MainGame.cs.
References Arkanoid.GameObjects.MapGenerator.GenerateMapWithBlocks().
         {
             List<Brick> map = mapGenerator.GenerateMapWithBlocks(7, 5, 5f, 5f);
             entitiesManager.AddEntity(map);
             physicsManager.AddPhysicsEntity(map);
         }
Initialize()
override void Arkanoid.Scenes.MainGame.Initialize () inline virtual
Initialize function. Invoked on start of the game
Reimplemented from Arkanoid.Scene.
Definition at line 97 of file MainGame.cs.
Referenced by Arkanoid.GameController.Initialize().
         {
             LoadTextures();
             LoadFonts();
             InitializeBackground();
             InitializePaddle();
             InitializeBall();
             InitializeMapGenerator();
             InitializeUI();
             PrepareNewGame();
             entities = entitiesManager.GetEntities();
         }
InitializeBackground()
void Arkanoid.Scenes.MainGame.InitializeBackground () inline private
Definition at line 135 of file MainGame.cs.
References Arkanoid.Resources.GameResources.BACKGROUND_TEXTURE.
         {
             Texture2D backgroundTexture = game.Content.Load<Texture2D>(GameResources.BACKGROUND_TEXTURE);
             background = new DrawableEntity(backgroundTexture, spriteBatch, game.ScreenCenter);
         }
InitializeBall()
void Arkanoid.Scenes.MainGame.InitializeBall () inline private
Definition at line 141 of file MainGame.cs.
References Arkanoid.Resources.GameResources.BALL_TEXTURE, Arkanoid.GameObjects.Ball.SetBounds(), and Arkanoid.Entity.Transform.
         {
             Texture2D ballTexture = game.Content.Load<Texture2D>(GameResources.BALL_TEXTURE);
             Vector2 position = game.ScreenCenter;
             ball = new Ball(spriteBatch, position, ballTexture, paddle);
             ball.Transform.Scale.X = 1f;
             ball.Transform.Scale.Y = 1f;
             ball.SetBounds(game.ScreenBounds);
         }
InitializeGameOverForeground()
void Arkanoid.Scenes.MainGame.InitializeGameOverForeground () inline private
Definition at line 196 of file MainGame.cs.
References Arkanoid.Resources.GameResources.GAMEOVER_FOREGROUND_TEXTURE.
         {
             Texture2D foregroundTexture = game.Content.Load<Texture2D>(GameResources.GAMEOVER_FOREGROUND_TEXTURE);
             gameOverForeground = new DrawableEntity(foregroundTexture, spriteBatch, game.ScreenCenter);
         }
InitializeHeartHP()
void Arkanoid.Scenes.MainGame.InitializeHeartHP () inline private
Definition at line 170 of file MainGame.cs.
References Arkanoid.Resources.GameResources.HEART_TEXTURE, and Arkanoid.Entity.Transform.
         {
             float scaleX = 0.5f;
             float scaleY = 0.5f;
             float offsetX = 10f;
             float offsetY = 10f;
             Texture2D heartTexture = game.Content.Load<Texture2D>(GameResources.HEART_TEXTURE);
             Vector2 position = new Vector2(game.ScreenBounds.Left + heartTexture.Width/2f*scaleX + offsetX, game.ScreenBounds.Top + heartTexture.Height/2f * scaleY + offsetY);
             hp = new HeartHP(heartTexture, spriteBatch, 0, position);
             hp.Transform.Scale.X = scaleX;
             hp.Transform.Scale.Y = scaleY;
             managerUI.AddEntity(hp);
         }
InitializeMapGenerator()
void Arkanoid.Scenes.MainGame.InitializeMapGenerator () inline private
Definition at line 202 of file MainGame.cs.
         {
             mapGenerator = new MapGenerator(game, spriteBatch, game.ScreenBounds);
         }
InitializePaddle()
void Arkanoid.Scenes.MainGame.InitializePaddle () inline private
Definition at line 151 of file MainGame.cs.
References Arkanoid.Resources.GameResources.PADDLE_TEXTURE, Arkanoid.GameObjects.Paddle.SetBounds(), and Arkanoid.Entity.Transform.
         {
             float scaleX = 1f;
             float scaleY = 1f;
             Texture2D paddleTexture = game.Content.Load<Texture2D>(GameResources.PADDLE_TEXTURE);
             Vector2 position = new Vector2(game.ScreenBounds.Right / 2f, game.ScreenBounds.Bottom-paddleTexture.Height/2 * scaleY);
             paddle = new Paddle(spriteBatch, position, paddleTexture);
             paddle.Transform.Scale.X = scaleX;
             paddle.Transform.Scale.Y = scaleY;
             paddle.SetBounds(game.ScreenBounds);
         }
InitializeTexts()
void Arkanoid.Scenes.MainGame.InitializeTexts () inline private
Definition at line 185 of file MainGame.cs.
References Arkanoid.Resources.GameResources.GAMEOVER_FONT, and Arkanoid.Resources.GameResources.RESTART_FONT.
         {
             SpriteFont gameOverFont = game.Content.Load<SpriteFont>(GameResources.GAMEOVER_FONT);
             SpriteFont restartFont = game.Content.Load<SpriteFont>(GameResources.RESTART_FONT);
             gameOverText = new TextLabel(GAME_OVER_TEXT, gameOverFont, spriteBatch, game.ScreenCenter - textSpace/2);
             Vector2 restartTextPosition = game.ScreenCenter + new Vector2(0, gameOverText.GetTextSize().Y) + textSpace/2;
             restartText = new TextLabel(RESTART_TEXT, restartFont, spriteBatch, restartTextPosition);
         }
InitializeUI()
void Arkanoid.Scenes.MainGame.InitializeUI () inline private
Definition at line 163 of file MainGame.cs.
         {
             InitializeHeartHP();
             InitializeGameOverForeground();
             InitializeTexts();
         }
LoadFonts()
void Arkanoid.Scenes.MainGame.LoadFonts () inline private
Definition at line 129 of file MainGame.cs.
References Arkanoid.Resources.GameResources.GAMEOVER_FONT, and Arkanoid.Resources.GameResources.RESTART_FONT.
         {
             game.Content.Load<SpriteFont>(GameResources.GAMEOVER_FONT);
             game.Content.Load<SpriteFont>(GameResources.RESTART_FONT);
         }
LoadTextures()
void Arkanoid.Scenes.MainGame.LoadTextures () inline private
Definition at line 114 of file MainGame.cs.
References Arkanoid.Resources.GameResources.BACKGROUND_TEXTURE, Arkanoid.Resources.GameResources.BALL_TEXTURE, Arkanoid.Resources.GameResources.BRICK_BLUE_TEXTURE, Arkanoid.Resources.GameResources.BRICK_GREEN_TEXTURE, Arkanoid.Resources.GameResources.BRICK_GREY_TEXTURE, Arkanoid.Resources.GameResources.BRICK_PURPLE_TEXTURE, Arkanoid.Resources.GameResources.BRICK_RED_TEXTURE, Arkanoid.Resources.GameResources.BRICK_YELLOW_TEXTURE, Arkanoid.Resources.GameResources.GAMEOVER_FOREGROUND_TEXTURE, Arkanoid.Resources.GameResources.HEART_TEXTURE, and Arkanoid.Resources.GameResources.PADDLE_TEXTURE.
         {
             game.Content.Load<Texture2D>(GameResources.BACKGROUND_TEXTURE);
             game.Content.Load<Texture2D>(GameResources.GAMEOVER_FOREGROUND_TEXTURE);
             game.Content.Load<Texture2D>(GameResources.HEART_TEXTURE);
             game.Content.Load<Texture2D>(GameResources.BALL_TEXTURE);
             game.Content.Load<Texture2D>(GameResources.PADDLE_TEXTURE);
             game.Content.Load<Texture2D>(GameResources.BRICK_RED_TEXTURE);
             game.Content.Load<Texture2D>(GameResources.BRICK_YELLOW_TEXTURE);
             game.Content.Load<Texture2D>(GameResources.BRICK_PURPLE_TEXTURE);
             game.Content.Load<Texture2D>(GameResources.BRICK_BLUE_TEXTURE);
             game.Content.Load<Texture2D>(GameResources.BRICK_GREEN_TEXTURE);
             game.Content.Load<Texture2D>(GameResources.BRICK_GREY_TEXTURE);
         }
PrepareNewGame()
void Arkanoid.Scenes.MainGame.PrepareNewGame () inline private
Definition at line 207 of file MainGame.cs.
References Arkanoid.GameObjects.Paddle.SetBall(), Arkanoid.GameObjects.HeartHP.SetHeart(), Arkanoid.GameObjects.Ball.SetOnPaddle(), and Arkanoid.Entity.Transform.
         {
             entitiesManager.Clear();
             physicsManager.Clear();
             managerUI.Clear();
             entitiesManager.AddEntity(background);
             entitiesManager.AddEntity(paddle);
             entitiesManager.AddEntity(ball);
             physicsManager.AddPhysicsEntity(paddle);
             physicsManager.AddPhysicsEntity(ball);
             managerUI.AddEntity(hp);
             paddle.Transform.Position.X = game.ScreenCenter.X;
             paddle.SetBall(ball);
             ball.SetOnPaddle(true);
             hp.SetHeart(INIT_LIFE_COUNT);
             GenerateMap();
             gameOver = false;
         }
Update()
override void Arkanoid.Scenes.MainGame.Update (GameTime gameTime) inline virtual
Every frame removes destroyed entities, invokes update and draw functions, checks collisions between physics bodies. Also updates and draws UI.
Parameters
gameTime object containing game time passed from class Game
Reimplemented from Arkanoid.Scene.
Definition at line 42 of file MainGame.cs.
Referenced by Arkanoid.GameController.Update().
         {
             if(!gameOver)
             {
                 base.Update(gameTime);
                 CheckBallLoss();
             }
             else
                 CheckRestartInput();
         }
Field Documentation
background
DrawableEntity Arkanoid.Scenes.MainGame.background private
Definition at line 24 of file MainGame.cs.
ball
Ball Arkanoid.Scenes.MainGame.ball private
Definition at line 25 of file MainGame.cs.
GAME_OVER_TEXT
const string Arkanoid.Scenes.MainGame.GAME_OVER_TEXT = "Game Over" private
Definition at line 18 of file MainGame.cs.
gameOver
bool Arkanoid.Scenes.MainGame.gameOver private
Definition at line 33 of file MainGame.cs.
gameOverForeground
DrawableEntity Arkanoid.Scenes.MainGame.gameOverForeground private
Definition at line 29 of file MainGame.cs.
gameOverText
TextLabel Arkanoid.Scenes.MainGame.gameOverText private
Definition at line 30 of file MainGame.cs.
hp
HeartHP Arkanoid.Scenes.MainGame.hp private
Definition at line 28 of file MainGame.cs.
INIT_LIFE_COUNT
const int Arkanoid.Scenes.MainGame.INIT_LIFE_COUNT = 3 private
Definition at line 20 of file MainGame.cs.
mapGenerator
MapGenerator Arkanoid.Scenes.MainGame.mapGenerator private
Definition at line 22 of file MainGame.cs.
paddle
Paddle Arkanoid.Scenes.MainGame.paddle private
Definition at line 26 of file MainGame.cs.
RESTART_TEXT
const string Arkanoid.Scenes.MainGame.RESTART_TEXT = "Press ENTER to restart" private
Definition at line 19 of file MainGame.cs.
restartText
TextLabel Arkanoid.Scenes.MainGame.restartText private
Definition at line 31 of file MainGame.cs.
textSpace
Vector2 Arkanoid.Scenes.MainGame.textSpace = new Vector2(0, 5) private
Definition at line 16 of file MainGame.cs.
The documentation for this class was generated from the following file:
Arcanoid/Scripts/Scenes/MainGame.cs