Arkanoid MONOGAME: Arkanoid.FadingInOutTextLabel Class Reference
Arkanoid.FadingInOutTextLabel Class Reference
Text label with fading in and fading out animation
Public Member Functions
FadingInOutTextLabel (string text, SpriteFont font, SpriteBatch spriteBatch, Vector2 position, double fadeTime)
override void Update (GameTime gameTime)
Function invoked every frame
Public Member Functions inherited from Arkanoid.TextLabel
TextLabel (string text, SpriteFont font, SpriteBatch spriteBatch, Vector2 position)
TextLabel (string text, SpriteFont font, SpriteBatch spriteBatch, Transform transform)
virtual void Draw (GameTime gameTime)
Method drawing object on the screen
void SetText (string text)
Set text to display
string GetText ()
Currently displayed text
Color GetColor ()
Current font color
void SetColor (Color color)
Set font color
Vector2 GetTextSize ()
Calculate current scene text real size
Public Member Functions inherited from Arkanoid.Entity
Entity ()
Entity (Vector2 position)
bool IsDestroyed ()
void Destroy ()
Takes object from manager invokes list
Private Member Functions
void AddDeltaTime (GameTime gameTime)
void ChangeTextAlpha ()
float CalculateAlpha ()
void CheckDeltaTime ()
Private Attributes
double deltaTime
bool fadeIn
double fadeTime
Additional Inherited Members
Data Fields inherited from Arkanoid.Entity
Transform Transform
string Tag
Detailed Description
Text label with fading in and fading out animation
Definition at line 11 of file FadingInOutTextLabel.cs.
Constructor & Destructor Documentation
FadingInOutTextLabel()
Arkanoid.FadingInOutTextLabel.FadingInOutTextLabel (string text, SpriteFont font, SpriteBatch spriteBatch, Vector2 position, double fadeTime) inline
Definition at line 17 of file FadingInOutTextLabel.cs.
References Arkanoid.FadingInOutTextLabel.deltaTime, Arkanoid.FadingInOutTextLabel.fadeIn, and Arkanoid.FadingInOutTextLabel.fadeTime.
                                                                                                                               : base(text, font, spriteBatch, position)
         {
             deltaTime = 0;
             this.fadeTime = fadeTime;
             fadeIn = true;
         }
Member Function Documentation
AddDeltaTime()
void Arkanoid.FadingInOutTextLabel.AddDeltaTime (GameTime gameTime) inline private
Definition at line 33 of file FadingInOutTextLabel.cs.
References Arkanoid.FadingInOutTextLabel.deltaTime, and Arkanoid.FadingInOutTextLabel.fadeTime.
Referenced by Arkanoid.FadingInOutTextLabel.Update().
         {
             deltaTime += gameTime.ElapsedGameTime.TotalSeconds;
             if (deltaTime > fadeTime)
                 deltaTime = fadeTime;
         }
CalculateAlpha()
float Arkanoid.FadingInOutTextLabel.CalculateAlpha () inline private
Definition at line 49 of file FadingInOutTextLabel.cs.
References Arkanoid.FadingInOutTextLabel.deltaTime, Arkanoid.FadingInOutTextLabel.fadeIn, and Arkanoid.FadingInOutTextLabel.fadeTime.
Referenced by Arkanoid.FadingInOutTextLabel.ChangeTextAlpha().
         {
             float alpha;
             if (fadeIn)
                 alpha = (float)(deltaTime / fadeTime);
             else
                 alpha = 1 - (float)(deltaTime / fadeTime);
             return alpha;
         }
ChangeTextAlpha()
void Arkanoid.FadingInOutTextLabel.ChangeTextAlpha () inline private
Definition at line 41 of file FadingInOutTextLabel.cs.
References Arkanoid.FadingInOutTextLabel.CalculateAlpha(), Arkanoid.TextLabel.GetColor(), and Arkanoid.TextLabel.SetColor().
Referenced by Arkanoid.FadingInOutTextLabel.Update().
         {
             float alpha = CalculateAlpha();
             Color textColor = GetColor();
             Color newColor = new Color(textColor, (float)alpha);
             SetColor(newColor);
         }
CheckDeltaTime()
void Arkanoid.FadingInOutTextLabel.CheckDeltaTime () inline private
Definition at line 61 of file FadingInOutTextLabel.cs.
References Arkanoid.FadingInOutTextLabel.deltaTime, Arkanoid.FadingInOutTextLabel.fadeIn, and Arkanoid.FadingInOutTextLabel.fadeTime.
Referenced by Arkanoid.FadingInOutTextLabel.Update().
         {
             if (deltaTime == fadeTime)
             {
                 fadeIn = !fadeIn;
                 deltaTime = 0;
             }
         }
Update()
override void Arkanoid.FadingInOutTextLabel.Update (GameTime gameTime) inline virtual
Function invoked every frame
Parameters
gameTime
Reimplemented from Arkanoid.Entity.
Definition at line 26 of file FadingInOutTextLabel.cs.
References Arkanoid.FadingInOutTextLabel.AddDeltaTime(), Arkanoid.FadingInOutTextLabel.ChangeTextAlpha(), and Arkanoid.FadingInOutTextLabel.CheckDeltaTime().
         {
             AddDeltaTime(gameTime);
             ChangeTextAlpha();
             CheckDeltaTime();
         }
Field Documentation
deltaTime
double Arkanoid.FadingInOutTextLabel.deltaTime private
Definition at line 13 of file FadingInOutTextLabel.cs.
Referenced by Arkanoid.FadingInOutTextLabel.AddDeltaTime(), Arkanoid.FadingInOutTextLabel.CalculateAlpha(), Arkanoid.FadingInOutTextLabel.CheckDeltaTime(), and Arkanoid.FadingInOutTextLabel.FadingInOutTextLabel().
fadeIn
bool Arkanoid.FadingInOutTextLabel.fadeIn private
Definition at line 14 of file FadingInOutTextLabel.cs.
Referenced by Arkanoid.FadingInOutTextLabel.CalculateAlpha(), Arkanoid.FadingInOutTextLabel.CheckDeltaTime(), and Arkanoid.FadingInOutTextLabel.FadingInOutTextLabel().
fadeTime
double Arkanoid.FadingInOutTextLabel.fadeTime private
Definition at line 15 of file FadingInOutTextLabel.cs.
Referenced by Arkanoid.FadingInOutTextLabel.AddDeltaTime(), Arkanoid.FadingInOutTextLabel.CalculateAlpha(), Arkanoid.FadingInOutTextLabel.CheckDeltaTime(), and Arkanoid.FadingInOutTextLabel.FadingInOutTextLabel().
The documentation for this class was generated from the following file:
Arcanoid/Scripts/Utils/GameObjects/FadingInOutTextLabel.cs