Arkanoid MONOGAME: Arkanoid.GameObjects.Paddle Class Reference
Arkanoid.GameObjects.Paddle Class Reference
Class representing moving arkanoid paddle
Public Member Functions
Paddle (SpriteBatch spriteBatch, Vector2 startPosition, Texture2D sprite)
void SetBounds (Rectangle bounds)
Method setting paddle restrains for moving (It cannot leave bounds - paddle stops on the edge)
Rectangle GetBounds ()
Returns current paddle bounds restrains
Vector2 GetDirection ()
Returns current paddle moving direction
void SetBall (Ball ball)
Sets ball to the paddle for future putting ball on this paddle after life loss
override void Update (GameTime gameTime)
Function invoked every frame
Rectangle GetCollider ()
Returns texture rectangular collider (from sprite renderer)
void OnCollision (IPhysicsBody collider)
Does nothing on collision
Public Member Functions inherited from Arkanoid.DrawableEntity
DrawableEntity (Texture2D sprite, SpriteBatch spriteBatch, Vector2 position)
virtual void Draw (GameTime gameTime)
Method drawing texture from sprite renderer on the screen
Public Member Functions inherited from Arkanoid.Entity
Entity ()
Entity (Vector2 position)
bool IsDestroyed ()
void Destroy ()
Takes object from manager invokes list
Private Member Functions
void CheckInput ()
void ThrowBall ()
Vector2 GetRandomBallDirection ()
void Move ()
void CheckBounds ()
void BounceFromTop ()
void BounceFromBottom ()
void BounceFromLeft ()
void BounceFromRight ()
Private Attributes
const float BALL_THROW_X_NOISE = 0.25f
const float PADDLE_SPEED = 400f
Rectangle screenBounds
Vector2 direction = Vector2.Zero
float deltaTime
Ball ball
Additional Inherited Members
Data Fields inherited from Arkanoid.DrawableEntity
SpriteRenderer SpriteRenderer
Data Fields inherited from Arkanoid.Entity
Transform Transform
string Tag
Detailed Description
Class representing moving arkanoid paddle
Definition at line 13 of file Paddle.cs.
Constructor & Destructor Documentation
Paddle()
Arkanoid.GameObjects.Paddle.Paddle (SpriteBatch spriteBatch, Vector2 startPosition, Texture2D sprite) inline
Definition at line 23 of file Paddle.cs.
                                                                                         : base(sprite, spriteBatch, startPosition)
         {
             Tag = "Paddle";
         }
Member Function Documentation
BounceFromBottom()
void Arkanoid.GameObjects.Paddle.BounceFromBottom () inline private
Definition at line 134 of file Paddle.cs.
         {
             direction = new Vector2(direction.X, -direction.Y);
         }
BounceFromLeft()
void Arkanoid.GameObjects.Paddle.BounceFromLeft () inline private
Definition at line 139 of file Paddle.cs.
         {
             direction = new Vector2(-direction.X, direction.Y);
         }
BounceFromRight()
void Arkanoid.GameObjects.Paddle.BounceFromRight () inline private
Definition at line 144 of file Paddle.cs.
         {
             direction = new Vector2(-direction.X, direction.Y);
         }
BounceFromTop()
void Arkanoid.GameObjects.Paddle.BounceFromTop () inline private
Definition at line 129 of file Paddle.cs.
         {
             direction = new Vector2(direction.X, -direction.Y);
         }
CheckBounds()
void Arkanoid.GameObjects.Paddle.CheckBounds () inline private
Definition at line 111 of file Paddle.cs.
References Arkanoid.Components.SpriteRenderer.GetWidth(), and Arkanoid.Components.Transform.Position.
         {
             if (Transform.Position.X - SpriteRenderer.GetWidth()/2 < screenBounds.Left)
             {
                 Transform.Position.X = screenBounds.Left + SpriteRenderer.GetWidth()/2;
                 BounceFromLeft();
             }
             else if(Transform.Position.X + SpriteRenderer.GetWidth()/2 > screenBounds.Right)
             {
                 Transform.Position.X = screenBounds.Right - SpriteRenderer.GetWidth()/2;
                 BounceFromRight();
             }
         }
CheckInput()
void Arkanoid.GameObjects.Paddle.CheckInput () inline private
Definition at line 76 of file Paddle.cs.
References Arkanoid.GameObjects.Ball.IsOnPaddle().
         {
             if (Keyboard.GetState().IsKeyDown(Keys.Left))
                 direction = -Vector2.UnitX;
             else if (Keyboard.GetState().IsKeyDown(Keys.Right))
                 direction = Vector2.UnitX;
             else
                 direction = Vector2.Zero;
             if(ball!=null && ball.IsOnPaddle() && Keyboard.GetState().IsKeyDown(Keys.Space))
                 ThrowBall();
         }
GetBounds()
Rectangle Arkanoid.GameObjects.Paddle.GetBounds () inline
Returns current paddle bounds restrains
Returns
rectangle of paddle movement bounds
Definition at line 41 of file Paddle.cs.
         {
             return screenBounds;
         }
GetCollider()
Rectangle Arkanoid.GameObjects.Paddle.GetCollider () inline
Returns texture rectangular collider (from sprite renderer)
Returns
sprite renderer rectangle
Implements Arkanoid.IPhysicsBody.
Definition at line 160 of file Paddle.cs.
References Arkanoid.Components.SpriteRenderer.GetRectangle().
Referenced by Arkanoid.GameObjects.Ball.OnCollision().
         {
             return SpriteRenderer.GetRectangle();
         }
GetDirection()
Vector2 Arkanoid.GameObjects.Paddle.GetDirection () inline
Returns current paddle moving direction
Returns
Definition at line 51 of file Paddle.cs.
Referenced by Arkanoid.GameObjects.Ball.OnCollision().
         {
             return direction;
         }
GetRandomBallDirection()
Vector2 Arkanoid.GameObjects.Paddle.GetRandomBallDirection () inline private
Definition at line 96 of file Paddle.cs.
         {
             float range = BALL_THROW_X_NOISE;
             Random random = new Random();
             float noiseX = (float)random.NextDouble() * (2 * range) - range;
             Vector2 dir = new Vector2(noiseX, (float)Math.Sqrt(1 - noiseX * noiseX));
             return dir;
         }
Move()
void Arkanoid.GameObjects.Paddle.Move () inline private
Definition at line 106 of file Paddle.cs.
References Arkanoid.Components.Transform.Position.
         {
             Transform.Position += direction * PADDLE_SPEED * deltaTime;
         }
OnCollision()
void Arkanoid.GameObjects.Paddle.OnCollision (IPhysicsBody collider) inline
Does nothing on collision
Parameters
collider
Implements Arkanoid.IPhysicsBody.
Definition at line 169 of file Paddle.cs.
         {
             //EMPTY
         }
SetBall()
void Arkanoid.GameObjects.Paddle.SetBall (Ball ball) inline
Sets ball to the paddle for future putting ball on this paddle after life loss
Parameters
ball
Definition at line 61 of file Paddle.cs.
Referenced by Arkanoid.Scenes.MainGame.PrepareNewGame().
         {
             this.ball = ball;
         }
SetBounds()
void Arkanoid.GameObjects.Paddle.SetBounds (Rectangle bounds) inline
Method setting paddle restrains for moving (It cannot leave bounds - paddle stops on the edge)
Parameters
bounds
Definition at line 32 of file Paddle.cs.
Referenced by Arkanoid.Scenes.MainGame.InitializePaddle().
         {
             this.screenBounds = bounds;
         }
ThrowBall()
void Arkanoid.GameObjects.Paddle.ThrowBall () inline private
Definition at line 89 of file Paddle.cs.
References Arkanoid.GameObjects.Ball.SetDirection(), and Arkanoid.GameObjects.Ball.SetOnPaddle().
         {
             Vector2 dir = GetRandomBallDirection();
             ball.SetDirection(dir);
             ball.SetOnPaddle(false);
         }
Update()
override void Arkanoid.GameObjects.Paddle.Update (GameTime gameTime) inline virtual
Function invoked every frame
Parameters
gameTime
Reimplemented from Arkanoid.Entity.
Definition at line 68 of file Paddle.cs.
         {
             deltaTime = (float)gameTime.ElapsedGameTime.TotalSeconds;
             CheckInput();
             Move();
             CheckBounds();
         }
Field Documentation
ball
Ball Arkanoid.GameObjects.Paddle.ball private
Definition at line 21 of file Paddle.cs.
BALL_THROW_X_NOISE
const float Arkanoid.GameObjects.Paddle.BALL_THROW_X_NOISE = 0.25f private
Definition at line 15 of file Paddle.cs.
deltaTime
float Arkanoid.GameObjects.Paddle.deltaTime private
Definition at line 20 of file Paddle.cs.
direction
Vector2 Arkanoid.GameObjects.Paddle.direction = Vector2.Zero private
Definition at line 19 of file Paddle.cs.
PADDLE_SPEED
const float Arkanoid.GameObjects.Paddle.PADDLE_SPEED = 400f private
Definition at line 16 of file Paddle.cs.
screenBounds
Rectangle Arkanoid.GameObjects.Paddle.screenBounds private
Definition at line 18 of file Paddle.cs.
The documentation for this class was generated from the following file:
Arcanoid/Scripts/Objects/Paddle.cs