Arkanoid MONOGAME: Arkanoid.GameObjects.Ball Class Reference
Arkanoid.GameObjects.Ball Class Reference
Class representing bouncing arkanoid ball in the game
Public Member Functions
Ball (SpriteBatch spriteBatch, Vector2 startPosition, Texture2D sprite, Paddle paddle)
void SetBounds (Rectangle bounds)
Method setting ball restrains for moving (It cannot leave bounds, also bounces of them)
Rectangle GetBounds ()
Returns current ball bounds restrains
bool IsOnPaddle ()
Returns true if ball if set on paddle (after life loss)
void SetOnPaddle (bool state)
Sets paddle on which the ball stays after life loss
void SetDirection (Vector2 direction)
Set ball moving direction
override void Update (GameTime gameTime)
Function invoked every frame
Rectangle GetCollider ()
Texture rectangular collider (from sprite renderer)
void OnCollision (IPhysicsBody collider)
If collider is paddle - bounces with friction from paddle If collider is brick - bounces with rebound angle
Public Member Functions inherited from Arkanoid.DrawableEntity
DrawableEntity (Texture2D sprite, SpriteBatch spriteBatch, Vector2 position)
virtual void Draw (GameTime gameTime)
Method drawing texture from sprite renderer on the screen
Public Member Functions inherited from Arkanoid.Entity
Entity ()
Entity (Vector2 position)
bool IsDestroyed ()
void Destroy ()
Takes object from manager invokes list
Private Member Functions
void OnPaddle ()
void Move ()
void CheckBounds ()
void BounceFromHorizontal ()
void BounceFromVertical ()
void BounceFromCollider (IPhysicsBody collider)
void BounceFromMovingVertCollider (IPhysicsBody collider, float verticalDirection)
Private Attributes
const float BALL_SPEED = 350f
Rectangle screenBounds
Vector2 direction
float deltaTime
Paddle paddle
bool isOnPaddle
Additional Inherited Members
Data Fields inherited from Arkanoid.DrawableEntity
SpriteRenderer SpriteRenderer
Data Fields inherited from Arkanoid.Entity
Transform Transform
string Tag
Detailed Description
Class representing bouncing arkanoid ball in the game
Definition at line 12 of file Ball.cs.
Constructor & Destructor Documentation
Ball()
Arkanoid.GameObjects.Ball.Ball (SpriteBatch spriteBatch, Vector2 startPosition, Texture2D sprite, Paddle paddle) inline
Definition at line 22 of file Ball.cs.
                                                                                                      : base(sprite, spriteBatch, startPosition)
         {
             Tag = "Ball";
             direction = Vector2.One;
             direction.Normalize();
             this.paddle = paddle;
         }
Member Function Documentation
BounceFromCollider()
void Arkanoid.GameObjects.Ball.BounceFromCollider (IPhysicsBody collider) inline private
Definition at line 183 of file Ball.cs.
References Arkanoid.IPhysicsBody.GetCollider(), Arkanoid.Components.SpriteRenderer.GetWidth(), and Arkanoid.Components.Transform.Position.
         {
             Rectangle colliderBody = collider.GetCollider();
             Vector2 dist = new Vector2((Transform.Position.X) - (colliderBody.Center.X),
                                        (Transform.Position.Y) - (colliderBody.Center.Y));
             float minDistX = (SpriteRenderer.GetWidth() / 2f + colliderBody.Width / 2f - 1);
             if (Math.Abs(dist.X) >= (minDistX))
             {
                 BounceFromVertical();
             }
             else
             {
                 BounceFromHorizontal();
             }
         }
BounceFromHorizontal()
void Arkanoid.GameObjects.Ball.BounceFromHorizontal () inline private
Definition at line 173 of file Ball.cs.
         {
             direction = new Vector2(direction.X, -direction.Y);
         }
BounceFromMovingVertCollider()
void Arkanoid.GameObjects.Ball.BounceFromMovingVertCollider (IPhysicsBody collider, float verticalDirection) inline private
Definition at line 200 of file Ball.cs.
References Arkanoid.IPhysicsBody.GetCollider(), and Arkanoid.Components.Transform.Position.
         {
             if (verticalDirection == 0) //Not moving
             {
                 BounceFromCollider(collider);
             }
             else //Moving to the one side -1 or 1
             {
                 Rectangle colliderBody = collider.GetCollider();
                 double offsetX = ((Transform.Position.X) - (colliderBody.Center.X)) / colliderBody.Width+ 0.5;
                 double rad = Math.PI * offsetX/3;
                 direction.X = (float)Math.Sin(rad)*verticalDirection;
                 direction.Y = (float)Math.Cos(rad)*(-1);
             }
         }
BounceFromVertical()
void Arkanoid.GameObjects.Ball.BounceFromVertical () inline private
Definition at line 178 of file Ball.cs.
         {
             direction = new Vector2(-direction.X, direction.Y);
         }
CheckBounds()
void Arkanoid.GameObjects.Ball.CheckBounds () inline private
Definition at line 101 of file Ball.cs.
References Arkanoid.Components.SpriteRenderer.GetHeight(), Arkanoid.Components.SpriteRenderer.GetWidth(), and Arkanoid.Components.Transform.Position.
         {
             if (Transform.Position.X  - SpriteRenderer.GetWidth()/2 < screenBounds.Left)
             {
                 Transform.Position.X = screenBounds.Left + SpriteRenderer.GetWidth()/2;
                 BounceFromVertical();
             }
             else if(Transform.Position.X + SpriteRenderer.GetWidth()/2 > screenBounds.Right)
             {
                 Transform.Position.X = screenBounds.Right - SpriteRenderer.GetWidth()/2;
                 BounceFromVertical();
             }
             if (Transform.Position.Y + SpriteRenderer.GetHeight()/2 > screenBounds.Bottom)
             {
                 Transform.Position.Y = screenBounds.Bottom - SpriteRenderer.GetHeight()/2;
                 BounceFromHorizontal();
             }
             else if (Transform.Position.Y  - SpriteRenderer.GetHeight()/2 < screenBounds.Top)
             {
                 Transform.Position.Y = screenBounds.Top + SpriteRenderer.GetHeight() / 2;
                 BounceFromHorizontal();
             }
         }
GetBounds()
Rectangle Arkanoid.GameObjects.Ball.GetBounds () inline
Returns current ball bounds restrains
Returns
rectangle of ball movement bounds
Definition at line 43 of file Ball.cs.
         {
             return screenBounds;
         }
GetCollider()
Rectangle Arkanoid.GameObjects.Ball.GetCollider () inline
Texture rectangular collider (from sprite renderer)
Returns
Implements Arkanoid.IPhysicsBody.
Definition at line 135 of file Ball.cs.
References Arkanoid.Components.SpriteRenderer.GetRectangle().
         {
             return SpriteRenderer.GetRectangle();
         }
IsOnPaddle()
bool Arkanoid.GameObjects.Ball.IsOnPaddle () inline
Returns true if ball if set on paddle (after life loss)
Returns
Definition at line 52 of file Ball.cs.
Referenced by Arkanoid.GameObjects.Paddle.CheckInput().
         {
             return isOnPaddle;
         }
Move()
void Arkanoid.GameObjects.Ball.Move () inline private
Definition at line 96 of file Ball.cs.
References Arkanoid.Components.Transform.Position.
         {
             Transform.Position += direction * BALL_SPEED * deltaTime;
         }
OnCollision()
void Arkanoid.GameObjects.Ball.OnCollision (IPhysicsBody collider) inline
If collider is paddle - bounces with friction from paddle If collider is brick - bounces with rebound angle
Parameters
collider
Implements Arkanoid.IPhysicsBody.
Definition at line 145 of file Ball.cs.
References Arkanoid.GameObjects.Paddle.GetCollider(), Arkanoid.GameObjects.Paddle.GetDirection(), and Arkanoid.Components.Transform.Position.
         {
             if (collider is Paddle)
             {
                 Paddle paddle = collider as Paddle;
                 Rectangle paddleBody = paddle.GetCollider();
                 Vector2 paddleDirection = paddle.GetDirection();
                 Rectangle ballBody = GetCollider();
                 int distY = (int)Math.Ceiling(Math.Abs((ballBody.Center.Y - BALL_SPEED * direction.Y * deltaTime) - paddleBody.Center.Y));
                 int minDistY = ballBody.Height / 2 + paddleBody.Height / 2;
                 if (distY >= minDistY) //Not ball loose so we can bounce from paddle
                 {
                     Transform.Position -= BALL_SPEED * direction * deltaTime;
                     BounceFromMovingVertCollider(collider, paddleDirection.X);
                 }
             } else if (collider is Brick)
             {
                 Transform.Position -= BALL_SPEED * direction * deltaTime;
                 BounceFromCollider(collider);
             }
         }
OnPaddle()
void Arkanoid.GameObjects.Ball.OnPaddle () inline private
Definition at line 90 of file Ball.cs.
References Arkanoid.Components.Transform.Position, Arkanoid.Components.Transform.Scale, Arkanoid.Components.SpriteRenderer.Sprite, and Arkanoid.Entity.Transform.
         {
             float offsetY = paddle.Transform.Position.Y - SpriteRenderer.Sprite.Height * Transform.Scale.Y;
             Transform.Position = new Vector2(paddle.Transform.Position.X, offsetY);
         }
SetBounds()
void Arkanoid.GameObjects.Ball.SetBounds (Rectangle bounds) inline
Method setting ball restrains for moving (It cannot leave bounds, also bounces of them)
Parameters
bounds
Definition at line 34 of file Ball.cs.
Referenced by Arkanoid.Scenes.MainGame.InitializeBall().
         {
             this.screenBounds = bounds;
         }
SetDirection()
void Arkanoid.GameObjects.Ball.SetDirection (Vector2 direction) inline
Set ball moving direction
Parameters
direction
Definition at line 70 of file Ball.cs.
Referenced by Arkanoid.GameObjects.Paddle.ThrowBall().
         {
             this.direction = direction;
         }
SetOnPaddle()
void Arkanoid.GameObjects.Ball.SetOnPaddle (bool state) inline
Sets paddle on which the ball stays after life loss
Parameters
state
Definition at line 61 of file Ball.cs.
Referenced by Arkanoid.Scenes.MainGame.CheckBallLoss(), Arkanoid.Scenes.MainGame.PrepareNewGame(), and Arkanoid.GameObjects.Paddle.ThrowBall().
         {
             isOnPaddle = state;
         }
Update()
override void Arkanoid.GameObjects.Ball.Update (GameTime gameTime) inline virtual
Function invoked every frame
Parameters
gameTime
Reimplemented from Arkanoid.Entity.
Definition at line 77 of file Ball.cs.
         {
             deltaTime = (float)gameTime.ElapsedGameTime.TotalSeconds;
             if(isOnPaddle)
             {
                 OnPaddle();
             } else
             {
                 Move();
                 CheckBounds();
             }
         }
Field Documentation
BALL_SPEED
const float Arkanoid.GameObjects.Ball.BALL_SPEED = 350f private
Definition at line 14 of file Ball.cs.
deltaTime
float Arkanoid.GameObjects.Ball.deltaTime private
Definition at line 18 of file Ball.cs.
direction
Vector2 Arkanoid.GameObjects.Ball.direction private
Definition at line 17 of file Ball.cs.
isOnPaddle
bool Arkanoid.GameObjects.Ball.isOnPaddle private
Definition at line 20 of file Ball.cs.
paddle
Paddle Arkanoid.GameObjects.Ball.paddle private
Definition at line 19 of file Ball.cs.
screenBounds
Rectangle Arkanoid.GameObjects.Ball.screenBounds private
Definition at line 16 of file Ball.cs.
The documentation for this class was generated from the following file:
Arcanoid/Scripts/Objects/Ball.cs