Arkanoid MONOGAME: Arkanoid.GameController Class Reference
Arkanoid.GameController Class Reference
Public Types
enum GameState { GameState.Menu, GameState.Game }
Public Member Functions
GameController ()
void SetState (GameState state)
GameState GetCurrentState ()
Data Fields
GraphicsDeviceManager Graphics
Rectangle ScreenBounds
Vector2 ScreenCenter
Protected Member Functions
override void Initialize ()
override void LoadContent ()
override void UnloadContent ()
override void Update (GameTime gameTime)
override void Draw (GameTime gameTime)
Private Member Functions
void InitializeScreenBounds ()
Private Attributes
GameState gameState
MainGame mainGameController
MainMenu mainMenuController
Detailed Description
Definition at line 8 of file GameController.cs.
Member Enumeration Documentation
GameState
enum Arkanoid.GameController.GameState strong
Enumerator
Menu
Game
Definition at line 14 of file GameController.cs.
         {
             Menu,
             Game
         }
Constructor & Destructor Documentation
GameController()
Arkanoid.GameController.GameController () inline
Definition at line 25 of file GameController.cs.
References Arkanoid.GameController.gameState, and Arkanoid.GameController.Graphics.
         {
             Graphics = new GraphicsDeviceManager(this);
             Graphics.PreferredBackBufferWidth = 640;
             Graphics.PreferredBackBufferHeight = 380;
             Content.RootDirectory = "Content";
             gameState = GameState.Menu;
         }
Member Function Documentation
Draw()
override void Arkanoid.GameController.Draw (GameTime gameTime) inline protected
Definition at line 79 of file GameController.cs.
References Arkanoid.Scene.Draw(), Arkanoid.Scenes.MainGame.Draw(), Arkanoid.GameController.gameState, Arkanoid.GameController.mainGameController, and Arkanoid.GameController.mainMenuController.
         {
             GraphicsDevice.Clear(Color.Black);
             switch (gameState)
             {
                 case GameState.Game:
                     mainGameController.Draw(gameTime);
                     break;
                 case GameState.Menu:
                     mainMenuController.Draw(gameTime);
                     break;
             }
             base.Draw(gameTime);
         }
GetCurrentState()
GameState Arkanoid.GameController.GetCurrentState () inline
Definition at line 100 of file GameController.cs.
References Arkanoid.GameController.gameState.
         {
             return gameState;
         }
Initialize()
override void Arkanoid.GameController.Initialize () inline protected
Definition at line 34 of file GameController.cs.
References Arkanoid.Scenes.MainMenu.Initialize(), Arkanoid.Scenes.MainGame.Initialize(), Arkanoid.GameController.InitializeScreenBounds(), Arkanoid.GameController.mainGameController, and Arkanoid.GameController.mainMenuController.
         {
             base.Initialize();
             InitializeScreenBounds();
             mainGameController = new MainGame(this);
             mainGameController.Initialize();
             mainMenuController = new MainMenu(this);
             mainMenuController.Initialize();
         }
InitializeScreenBounds()
void Arkanoid.GameController.InitializeScreenBounds () inline private
Definition at line 45 of file GameController.cs.
References Arkanoid.GameController.ScreenBounds, and Arkanoid.GameController.ScreenCenter.
Referenced by Arkanoid.GameController.Initialize().
         {
             ScreenBounds = GraphicsDevice.PresentationParameters.Bounds;
             ScreenCenter = new Vector2(ScreenBounds.Width / 2, ScreenBounds.Height / 2);
         }
LoadContent()
override void Arkanoid.GameController.LoadContent () inline protected
Definition at line 51 of file GameController.cs.
         {
             // TODO: Load any non ContentManager content here
         }
SetState()
void Arkanoid.GameController.SetState (GameState state) inline
Definition at line 95 of file GameController.cs.
References Arkanoid.GameController.gameState.
         {
             gameState = state;
         }
UnloadContent()
override void Arkanoid.GameController.UnloadContent () inline protected
Definition at line 56 of file GameController.cs.
         {
             // TODO: Unload any non ContentManager content here
         }
Update()
override void Arkanoid.GameController.Update (GameTime gameTime) inline protected
Definition at line 61 of file GameController.cs.
References Arkanoid.GameController.gameState, Arkanoid.GameController.mainGameController, Arkanoid.GameController.mainMenuController, Arkanoid.Scenes.MainMenu.Update(), and Arkanoid.Scenes.MainGame.Update().
         {
             if (GamePad.GetState(PlayerIndex.One).Buttons.Back == ButtonState.Pressed || Keyboard.GetState().IsKeyDown(Keys.Escape))
                 gameState = GameState.Menu;
             switch (gameState)
             {
                 case GameState.Game:
                     mainGameController.Update(gameTime);
                     break;
                 case GameState.Menu:
                     mainMenuController.Update(gameTime);
                     break;
             }
             base.Update(gameTime);
         }
Field Documentation
gameState
GameState Arkanoid.GameController.gameState private
Definition at line 20 of file GameController.cs.
Referenced by Arkanoid.GameController.Draw(), Arkanoid.GameController.GameController(), Arkanoid.GameController.GetCurrentState(), Arkanoid.GameController.SetState(), and Arkanoid.GameController.Update().
Graphics
GraphicsDeviceManager Arkanoid.GameController.Graphics
Definition at line 10 of file GameController.cs.
Referenced by Arkanoid.GameController.GameController().
mainGameController
MainGame Arkanoid.GameController.mainGameController private
Definition at line 22 of file GameController.cs.
Referenced by Arkanoid.GameController.Draw(), Arkanoid.GameController.Initialize(), and Arkanoid.GameController.Update().
mainMenuController
MainMenu Arkanoid.GameController.mainMenuController private
Definition at line 23 of file GameController.cs.
Referenced by Arkanoid.GameController.Draw(), Arkanoid.GameController.Initialize(), and Arkanoid.GameController.Update().
ScreenBounds
Rectangle Arkanoid.GameController.ScreenBounds
Definition at line 11 of file GameController.cs.
Referenced by Arkanoid.GameController.InitializeScreenBounds().
ScreenCenter
Vector2 Arkanoid.GameController.ScreenCenter
Definition at line 12 of file GameController.cs.
Referenced by Arkanoid.GameController.InitializeScreenBounds().
The documentation for this class was generated from the following file:
Arcanoid/GameController.cs