Arkanoid MONOGAME: Arkanoid.Managers.PhysicsManager Class Reference
Arkanoid.Managers.PhysicsManager Class Reference
Class for managing physics and collisions between IPhysicsBody objects in the scene
Public Member Functions
PhysicsManager ()
void Update (GameTime gameTime)
Update checking collisions of bodies in the manager
void AddPhysicsEntity (IPhysicsBody physicsEntity)
Adds physics body to the manager (It doesn't have to be an entity!)
void AddPhysicsEntity< T > (List< T > physicsEntitiesList)
Adds list of physics body to the manager (It doesn't have to be an entities list!)
void RemovePhysicsEntity (IPhysicsBody physicsEntity)
Removes body from physics manager
void Clear ()
Removes every body from manager
Private Member Functions
void CheckCollisions ()
Private Attributes
List< IPhysicsBody > physicsEntities
Detailed Description
Class for managing physics and collisions between IPhysicsBody objects in the scene
Definition at line 11 of file PhysicsManager.cs.
Constructor & Destructor Documentation
PhysicsManager()
Arkanoid.Managers.PhysicsManager.PhysicsManager () inline
Definition at line 15 of file PhysicsManager.cs.
         {
             physicsEntities = new List<IPhysicsBody>();
         }
Member Function Documentation
AddPhysicsEntity()
void Arkanoid.Managers.PhysicsManager.AddPhysicsEntity (IPhysicsBody physicsEntity) inline
Adds physics body to the manager (It doesn't have to be an entity!)
Parameters
physicsEntity
Definition at line 54 of file PhysicsManager.cs.
         {
             physicsEntities.Add(physicsEntity);
         }
AddPhysicsEntity< T >()
void Arkanoid.Managers.PhysicsManager.AddPhysicsEntity< T > (List< T > physicsEntitiesList) inline
Adds list of physics body to the manager (It doesn't have to be an entities list!)
Template Parameters
T
Parameters
physicsEntitiesList
Type Constraints
T : IPhysicsBody
Definition at line 64 of file PhysicsManager.cs.
                                                                              : IPhysicsBody
         {
             for (int i = 0; i < physicsEntitiesList.Count; i++)
                 AddPhysicsEntity(physicsEntitiesList[i]);
         }
CheckCollisions()
void Arkanoid.Managers.PhysicsManager.CheckCollisions () inline private
Definition at line 31 of file PhysicsManager.cs.
References Arkanoid.IPhysicsBody.OnCollision().
         {
             for (int i = 0; i < physicsEntities.Count; i++)
             {
                 for (int j = 0; j < physicsEntities.Count; j++)
                 {
                     if (!physicsEntities[i].Equals(physicsEntities[j]) && physicsEntities[i].GetCollider().Intersects(physicsEntities[j].GetCollider()))
                     {
                         IPhysicsBody collider2 = physicsEntities[j];
                         IPhysicsBody collider1 = physicsEntities[i];
                         collider1.OnCollision(collider2);
                         collider2.OnCollision(collider1);
                     }
                 }
             }
         }
Clear()
void Arkanoid.Managers.PhysicsManager.Clear () inline
Removes every body from manager
Definition at line 82 of file PhysicsManager.cs.
         {
             physicsEntities.Clear();
         }
RemovePhysicsEntity()
void Arkanoid.Managers.PhysicsManager.RemovePhysicsEntity (IPhysicsBody physicsEntity) inline
Removes body from physics manager
Parameters
physicsEntity
Definition at line 74 of file PhysicsManager.cs.
Referenced by Arkanoid.Scene.DestroyEntity().
         {
             physicsEntities.Remove(physicsEntity);
         }
Update()
void Arkanoid.Managers.PhysicsManager.Update (GameTime gameTime) inline
Update checking collisions of bodies in the manager
Parameters
gameTime object containing game time passed from class Game
Implements Arkanoid.IUpdateable.
Definition at line 26 of file PhysicsManager.cs.
Referenced by Arkanoid.Scene.Update().
         {
             CheckCollisions();
         }
Field Documentation
physicsEntities
List<IPhysicsBody> Arkanoid.Managers.PhysicsManager.physicsEntities private
Definition at line 13 of file PhysicsManager.cs.
The documentation for this class was generated from the following file:
Arcanoid/Scripts/Utils/Managers/PhysicsManager.cs