Arkanoid MONOGAME: Arkanoid.Scene Class Reference
Arkanoid.Scene Class Reference
Basic class for scene in game
Public Member Functions
Scene (GameController game)
virtual void Update (GameTime gameTime)
Every frame removes destroyed entities, invokes update and draw functions, checks collisions between physics bodies. Also updates and draws UI.
void DestroyEntity (Entity entity)
Removes entity from every possible manager
virtual void Draw (GameTime gameTime)
Draws entities and then draws UI
virtual void Initialize ()
Initialize function. Invoked on start of the game
Protected Attributes
GameController game
SpriteBatch spriteBatch
EntitiesManager managerUI
EntitiesManager entitiesManager
PhysicsManager physicsManager
List< Entity > entities
Detailed Description
Basic class for scene in game
Definition at line 12 of file Scene.cs.
Constructor & Destructor Documentation
Scene()
Arkanoid.Scene.Scene (GameController game) inline
Definition at line 21 of file Scene.cs.
References Arkanoid.Scene.entitiesManager, Arkanoid.Scene.game, Arkanoid.Scene.managerUI, and Arkanoid.Scene.physicsManager.
         {
             this.game = game;
             this.spriteBatch = new SpriteBatch(game.GraphicsDevice);
             managerUI = new EntitiesManager();
             entitiesManager = new EntitiesManager();
             physicsManager = new PhysicsManager();
         }
Member Function Documentation
DestroyEntity()
void Arkanoid.Scene.DestroyEntity (Entity entity) inline
Removes entity from every possible manager
Parameters
entity entity to be removed
Definition at line 57 of file Scene.cs.
References Arkanoid.Scene.entitiesManager, Arkanoid.Scene.physicsManager, Arkanoid.Managers.EntitiesManager.RemoveEntity(), and Arkanoid.Managers.PhysicsManager.RemovePhysicsEntity().
Referenced by Arkanoid.Scene.Update().
         {
             entitiesManager.RemoveEntity(entity);
             if (entity is IPhysicsBody)
                 physicsManager.RemovePhysicsEntity((IPhysicsBody)entity);
         }
Draw()
virtual void Arkanoid.Scene.Draw (GameTime gameTime) inline virtual
Draws entities and then draws UI
Parameters
gameTime object containing game time passed from class Game
Implements Arkanoid.IDrawable.
Reimplemented in Arkanoid.Scenes.MainGame.
Definition at line 72 of file Scene.cs.
Referenced by Arkanoid.GameController.Draw().
         {
             spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.NonPremultiplied);
             entitiesManager.Draw(gameTime);
             spriteBatch.End();
             spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.NonPremultiplied);
             managerUI.Draw(gameTime);
             spriteBatch.End();
         }
Initialize()
virtual void Arkanoid.Scene.Initialize () inline virtual
Initialize function. Invoked on start of the game
Reimplemented in Arkanoid.Scenes.MainGame, and Arkanoid.Scenes.MainMenu.
Definition at line 90 of file Scene.cs.
         {
             //Dummy
         }
Update()
virtual void Arkanoid.Scene.Update (GameTime gameTime) inline virtual
Every frame removes destroyed entities, invokes update and draw functions, checks collisions between physics bodies. Also updates and draws UI.
Parameters
gameTime object containing game time passed from class Game
Implements Arkanoid.IUpdateable.
Reimplemented in Arkanoid.Scenes.MainGame, and Arkanoid.Scenes.MainMenu.
Definition at line 36 of file Scene.cs.
References Arkanoid.Scene.DestroyEntity(), Arkanoid.Scene.entities, Arkanoid.Scene.entitiesManager, Arkanoid.Scene.managerUI, Arkanoid.Scene.physicsManager, Arkanoid.Managers.PhysicsManager.Update(), and Arkanoid.Managers.EntitiesManager.Update().
         {
             for (int i = 0; i < entities.Count; i++)
             {
                 if (entities[i].IsDestroyed())
                 {
                     DestroyEntity(entities[i]);
                     i--;
                 }
             }
             entitiesManager.Update(gameTime);
             physicsManager.Update(gameTime);
             managerUI.Update(gameTime);
         }
Field Documentation
entities
List<Entity> Arkanoid.Scene.entities protected
Definition at line 19 of file Scene.cs.
Referenced by Arkanoid.Scene.Update().
entitiesManager
EntitiesManager Arkanoid.Scene.entitiesManager protected
Definition at line 17 of file Scene.cs.
Referenced by Arkanoid.Scene.DestroyEntity(), Arkanoid.Scene.Scene(), and Arkanoid.Scene.Update().
game
GameController Arkanoid.Scene.game protected
Definition at line 14 of file Scene.cs.
Referenced by Arkanoid.Scene.Scene().
managerUI
EntitiesManager Arkanoid.Scene.managerUI protected
Definition at line 16 of file Scene.cs.
Referenced by Arkanoid.Scene.Scene(), and Arkanoid.Scene.Update().
physicsManager
PhysicsManager Arkanoid.Scene.physicsManager protected
Definition at line 18 of file Scene.cs.
Referenced by Arkanoid.Scene.DestroyEntity(), Arkanoid.Scene.Scene(), and Arkanoid.Scene.Update().
spriteBatch
SpriteBatch Arkanoid.Scene.spriteBatch protected
Definition at line 15 of file Scene.cs.
The documentation for this class was generated from the following file:
Arcanoid/Scripts/Utils/Abstract Classes/Scene.cs