Arkanoid MONOGAME: Arkanoid.GameObjects.HeartHP Class Reference
Arkanoid.GameObjects.HeartHP Class Reference
Class for heart hp on UI, contains life count
Public Member Functions
HeartHP (Texture2D heartTexture, SpriteBatch spriteBatch, int lifeCount, Vector2 position)
int GetLifeCount ()
void AddHeart ()
void RemoveHeart ()
void SetHeart (int count)
override void Draw (GameTime gameTime)
Draws number of hearts equal to life count
Public Member Functions inherited from Arkanoid.DrawableEntity
DrawableEntity (Texture2D sprite, SpriteBatch spriteBatch, Vector2 position)
Public Member Functions inherited from Arkanoid.Entity
Entity ()
Entity (Vector2 position)
virtual void Update (GameTime gameTime)
Function invoked every frame
bool IsDestroyed ()
void Destroy ()
Takes object from manager invokes list
Private Attributes
const int SPACE_X = 5
int lifeCount
Vector2 startPosition
Additional Inherited Members
Data Fields inherited from Arkanoid.DrawableEntity
SpriteRenderer SpriteRenderer
Data Fields inherited from Arkanoid.Entity
Transform Transform
string Tag
Detailed Description
Class for heart hp on UI, contains life count
Definition at line 13 of file HeartHP.cs.
Constructor & Destructor Documentation
HeartHP()
Arkanoid.GameObjects.HeartHP.HeartHP (Texture2D heartTexture, SpriteBatch spriteBatch, int lifeCount, Vector2 position) inline
Definition at line 20 of file HeartHP.cs.
                                                                                                          : base(heartTexture, spriteBatch, position)
         {
             startPosition = position;
             this.lifeCount = lifeCount;
         }
Member Function Documentation
AddHeart()
void Arkanoid.GameObjects.HeartHP.AddHeart () inline
Definition at line 31 of file HeartHP.cs.
         {
             lifeCount++;
         }
Draw()
override void Arkanoid.GameObjects.HeartHP.Draw (GameTime gameTime) inline virtual
Draws number of hearts equal to life count
Parameters
gameTime
Reimplemented from Arkanoid.DrawableEntity.
Definition at line 50 of file HeartHP.cs.
References Arkanoid.Components.SpriteRenderer.DrawSprite(), Arkanoid.Components.SpriteRenderer.GetWidth(), and Arkanoid.Components.Transform.Position.
         {
             for(int i=0; i<lifeCount; i++)
             {
                 SpriteRenderer.DrawSprite();
                 Transform.Position.X += (SpriteRenderer.GetWidth() + SPACE_X);
             }
             Transform.Position = startPosition;
         }
GetLifeCount()
int Arkanoid.GameObjects.HeartHP.GetLifeCount () inline
Definition at line 26 of file HeartHP.cs.
Referenced by Arkanoid.Scenes.MainGame.CheckBallLoss().
         {
             return lifeCount;
         }
RemoveHeart()
void Arkanoid.GameObjects.HeartHP.RemoveHeart () inline
Definition at line 36 of file HeartHP.cs.
Referenced by Arkanoid.Scenes.MainGame.CheckBallLoss().
         {
             lifeCount--;
         }
SetHeart()
void Arkanoid.GameObjects.HeartHP.SetHeart (int count) inline
Definition at line 41 of file HeartHP.cs.
Referenced by Arkanoid.Scenes.MainGame.PrepareNewGame().
         {
             lifeCount = count;
         }
Field Documentation
lifeCount
int Arkanoid.GameObjects.HeartHP.lifeCount private
Definition at line 17 of file HeartHP.cs.
SPACE_X
const int Arkanoid.GameObjects.HeartHP.SPACE_X = 5 private
Definition at line 15 of file HeartHP.cs.
startPosition
Vector2 Arkanoid.GameObjects.HeartHP.startPosition private
Definition at line 18 of file HeartHP.cs.
The documentation for this class was generated from the following file:
Arcanoid/Scripts/Objects/HeartHP.cs