Arkanoid MONOGAME: Arkanoid.IPhysicsBody Interface Reference
Arkanoid.IPhysicsBody Interface Reference
Interface for objects with physics on the screen
Public Member Functions
Rectangle GetCollider ()
Method returning collider
void OnCollision (IPhysicsBody collider)
Trigger on collision
Detailed Description
Interface for objects with physics on the screen
Definition at line 9 of file IPhysicsBody.cs.
Member Function Documentation
GetCollider()
Rectangle Arkanoid.IPhysicsBody.GetCollider ()
Method returning collider
Implemented in Arkanoid.GameObjects.Paddle, Arkanoid.GameObjects.Ball, and Arkanoid.GameObjects.Brick.
Referenced by Arkanoid.GameObjects.Ball.BounceFromCollider(), and Arkanoid.GameObjects.Ball.BounceFromMovingVertCollider().
OnCollision()
void Arkanoid.IPhysicsBody.OnCollision (IPhysicsBody collider)
Trigger on collision
Parameters
collider body triggering collision
Implemented in Arkanoid.GameObjects.Paddle, Arkanoid.GameObjects.Ball, and Arkanoid.GameObjects.Brick.
Referenced by Arkanoid.Managers.PhysicsManager.CheckCollisions().
The documentation for this interface was generated from the following file:
Arcanoid/Scripts/Utils/Interfaces/IPhysicsBody.cs